### ISSUE TITLE
Some errors on the Pi Zero

### ISSUE THREAD

**Issue by Infer4Y** [ian-antking/cardkb#1]
So I installed your project on the pi zero using Raspbian lite and I get this error with running it.
```Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "cardkb/__main__.py", line 11, in <module>
    bus = smbus.SMBus(i2c_bus)
FileNotFoundError: [Errno 2] No such file or directory
^C
[1]+  Exit 1                  sudo python3 cardkb 1
```
I did install python3-smbus and uinput as well.

**Comment by ian-antking** [comment]
Think I had a similar issue trying to get it to work with the hyper pixel screen. Are you setting the i2c bus in the arguments?

**Comment by Infer4Y** [comment]
yes as 1

**Comment by ian-antking** [comment]
What files do you get if you run `ls /dev/i2c*`?

**Comment by Infer4Y** [comment]
`/dev/i2c-1`

**Comment by Infer4Y** [comment]
Okay now I fixed that one error by doing `python3 cardkb -1 &`, but then a new error arises. 
 ```Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "cardkb/__main__.py", line 15, in <module>
    with Device(keys) as device:
  File "/usr/local/lib/python3.7/dist-packages/uinput/__init__.py", line 178, in __init__
    self.__uinput_fd = fd or fdopen()
  File "/usr/local/lib/python3.7/dist-packages/uinput/__init__.py", line 84, in fdopen
    return _libsuinput.suinput_open()
  File "/usr/local/lib/python3.7/dist-packages/uinput/__init__.py", line 70, in _open_error_handler
    raise OSError(code, msg)
OSError: [Errno 19] Failed to open the uinput device: No such device```

**Comment by Infer4Y** [comment]
After that I did `lsmod | grep uinput` to check if uinput was loaded then `sudo modprobe uinput` if it wasn't. And running it again leads me to this error. 
```Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "cardkb/__main__.py", line 17, in <module>
    data = bus.read_byte(address)
OSError: [Errno 9] Bad file descriptor
```

**Comment by ian-antking** [comment]
is that running `python3 cardkb -1 &` or `python3 cardkb 1 &`? Am wondering if the problems was the `uinput` module wasn't loaded. 

Also, just running `python3 cardkb &` will default to `i2c-1`. It might be worth giving that a go.

**Comment by Infer4Y** [comment]
`python3 cardkb -1 &` So `python3 cardkb 1 &` tends to error for me with 
``` 
File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "cardkb/__main__.py", line 11, in <module>
    bus = smbus.SMBus(i2c_bus)
FileNotFoundError: [Errno 2] No such file or directory
^C
[1]+  Exit 1                  sudo python3 cardkb 1 
```

Weird just started working, with `python3 cardkb 1 &`.

**Comment by ian-antking** [comment]
Glad it’s working for you. 

Will update `README` to go through installing `uinput`.

**Comment by Infer4Y** [comment]
Also To get it started with the pi I added the lines as follows to `/etc/rc.local`.
```
...
sudo modprobe uinput
python3 /home/pi/cardkb 1 &
...
exit 0
```
